% ======= MODEL TRAINING ========
%% UNPACK DATASTORE
datastore_path = 'C:\Ovarian cancer project\Adipocyte dataset\train\final_data_v2';
images_path = 'C:\Ovarian cancer project\Adipocyte dataset\train\images';

ds = fileDatastore(datastore_path, ...
    ReadFcn=@(x)datasetReader(x,images_path));

data = preview(ds)

%%
options = trainingOptions("sgdm", ...
    InitialLearnRate=0.001, ...
    LearnRateSchedule="piecewise", ...
    LearnRateDropPeriod=1, ...
    LearnRateDropFactor=0.95, ...
    Plot="none", ...
    Momentum=0.9, ...
    MaxEpochs=200, ...
    MiniBatchSize=2, ...
    BatchNormalizationStatistics="moving", ...
    ResetInputNormalization=false, ...
    ExecutionEnvironment="gpu", ...
    VerboseFrequency=50);

trainClassNames = "Adipocyte";
imageSizeTrain = [1024 1024 3];
net = maskrcnn("resnet50-coco",trainClassNames,InputSize=imageSizeTrain);
%%
doTraining = true;
if doTraining
    [net,info] = trainMaskRCNN(ds,net,options,FreezeSubNetwork="backbone");
    modelDateTime = string(datetime("now",Format="yyyy-MM-dd-HH-mm-ss"));
    save("AdipocytetrainedMaskRCNN-"+modelDateTime+".mat","net", "info");
end